name: cgzsl
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - matplotlib=3.5.0
  - numpy=1.20.1
  - pandas=1.4.1
  - python=3.8.8
  - python-dateutil=2.8.2
  - pytorch=1.4.0
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - seaborn=0.11.2
  - torchaudio=0.4.0
  - torchvision=0.5.0
  - pip=21.2.4
  - pip:
    - easydict==1.9
    - plotly==5.6.0
    - pyyaml==6.0
    - randomname==0.1.5
    - tqdm==4.64.0

